package be.ugent.ledc.core.operators.metric;


/**
 * General interface for measuring the distance between two objects of type <code>T</code>. The result is expressed in
 * a value of type <code>N</code>.
 * @author antoon
 * @param <N> The type of result generated by this metric
 * @param <T> The type of objects that are compared under this metric
 */
public interface Metric<N extends Number,T>
{
    /**
     * Calculate the distance, expressed in value of type O, between two objects of type T.
     * @param o1
     * @param o2
     * @return
     */
    public N distance(T o1, T o2);
}
