package be.ugent.ledc.core.binding.jdbc;

import be.ugent.ledc.core.binding.BindingException;
import be.ugent.ledc.core.binding.DataWriteException;
import be.ugent.ledc.core.binding.jdbc.agents.DMLGenerator;
import be.ugent.ledc.core.binding.jdbc.schema.TableSchema;
import be.ugent.ledc.core.dataset.DataObject;
import be.ugent.ledc.core.dataset.Dataset;
import be.ugent.ledc.core.dataset.SimpleDataset;
import be.ugent.ledc.core.dataset.contractors.TypeContractorFactory;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

public class JDBCDataWriter extends JDBCOperator
{    
    private static final Logger LOGGER = Logger.getLogger(JDBCDataWriter.class.getName());
    
    private final TableSchema targetTable;

    private final boolean autoGeneratedKeys;
    
    private final PreparedStatement insertStatement;
    
    private final List<String> tableAttributes;

    private int maxBatchSize = 100000;

    public JDBCDataWriter(JDBCBinder binder, TableSchema targetTable, boolean autoGeneratedKeys) throws DataWriteException
    {
        super(binder);
        this.targetTable = targetTable;
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.tableAttributes = targetTable
            .getAttributeNames()
            .stream()
            .filter(a -> !this.autoGeneratedKeys || !targetTable.isKeyAttribute(a))
            .collect(Collectors.toList());
        this.insertStatement = initPreparedStatement();
    }

    public SimpleDataset writeData(Dataset dataset) throws DataWriteException, BindingException {
        try
        {
            getConnection().setAutoCommit(false);

            //Catch generated keys
            SimpleDataset generatedKeys = new SimpleDataset();

            int batchSize = 0;
            
            for (DataObject o : dataset.getDataObjects())
            {
                //Create a list of parameters, in the order indicated by table Attributes
                //For unspecified attributes, we check if a default value can be inserted
                List parameters = this.tableAttributes
                    .stream()
                    .map(a -> o.get(a) == null && targetTable.getAttributeProperty(a, TableSchema.PROP_DEFAULT_VALUE) != null 
                            ? targetTable.getAttributeProperty(a, TableSchema.PROP_DEFAULT_VALUE)
                            : convertToSqlType(o, a))
                    .collect(Collectors.toList());
                
                //Pass the parameters to the insert statement
                for (int i = 0; i < this.tableAttributes.size(); i++)
                {
                    DMLGenerator.setParameter(insertStatement, i + 1, parameters.get(i));
                }
                
                //Add the parameters to the batch of the prepared statement
                this.insertStatement.addBatch();
                
                //Increase the batch counter
                batchSize++;
                
                if (batchSize >= maxBatchSize)
                {
                    LOGGER.log(Level.INFO, "Reached batch limit {0}: pushing batch.", maxBatchSize);
                    generatedKeys.unionAll(push());
                    batchSize = 0;
                }
            }

            //Check if we need to flush a remaining batch.
            if(batchSize > 0)
            {
                generatedKeys.unionAll(push());
            }

            getConnection().setAutoCommit(true);

            return generatedKeys;
        }
        catch (SQLException ex)
        {
            //System.out.println(ex.getNextException().getMessage());
            throw new DataWriteException(ex);
        }
    }
   
    private SimpleDataset push() throws DataWriteException
    {
        try
        {         
            SimpleDataset generatedKeys = new SimpleDataset();
            
            //Execute batch
            insertStatement.executeBatch();
            
            if(autoGeneratedKeys)
            {
                //Fetch generated keys
                ResultSet keys = insertStatement.getGeneratedKeys();

                while (keys.next())
                {
                    DataObject generatedKey = new DataObject();
                    
                    for (String attributeName : targetTable.getPrimaryKey())
                    {
                        generatedKey.set(attributeName, keys.getObject(attributeName));
                    }
                    
                    generatedKeys.addDataObject(generatedKey);
                }
            }
            
            //Commit changes
            LOGGER.log(Level.INFO, "Commiting current batch.");
            getConnection().commit();
            
            return generatedKeys;
        }
        catch (SQLException | BindingException ex)
        {
            throw new DataWriteException(ex);
        }
    }
    
    public int getMaxBatchSize()
    {
        return maxBatchSize;
    }

    public void setMaxBatchSize(int maxBatchSize)
    {
        this.maxBatchSize = maxBatchSize;
    }
    
    public TableSchema getTargetTable()
    {
        return targetTable;
    }

    private PreparedStatement initPreparedStatement() throws DataWriteException
    {
        try
        {
            //Get a generator for writing prepared insert code
            DMLGenerator dmlGenerator = new DMLGenerator(
                getBinder().
                getRdb().
                getVendor().
                getAgent().escaping());
            
            return getConnection()
                .prepareStatement(dmlGenerator
                    .prepareInsertCode(
                        targetTable.getName(),
                        tableAttributes),
                        autoGeneratedKeys ?
                            Statement.RETURN_GENERATED_KEYS :
                            Statement.NO_GENERATED_KEYS);
        }
        catch (BindingException | SQLException ex)
        {
            throw new DataWriteException(ex);
        } 
    }
    
     private Object convertToSqlType(DataObject o, String attribute)
    {
        if(o.get(attribute) == null)
            return null;
        
        if(TypeContractorFactory.DATE.test(o.get(attribute)))
            return java.sql.Date.valueOf(TypeContractorFactory.DATE.getFromDataObject(o, attribute));
        
        if(TypeContractorFactory.TIME.test(o.get(attribute)))
            return java.sql.Time.valueOf(TypeContractorFactory.TIME.getFromDataObject(o, attribute));
        
        if(TypeContractorFactory.DATETIME.test(o.get(attribute)))
            return java.sql.Timestamp.valueOf(TypeContractorFactory.DATETIME.getFromDataObject(o, attribute));
    
        //Return as is
        return o.get(attribute);
    }
}
