package be.ugent.ledc.sigma.datastructures.fptree;

import java.util.*;

/**
 * This class represents a Frequent-Pattern Tree object with FPNode values of type I
 *
 * @param <I> Datatype of FPNode values
 */
public class FPTree<I> {

    /**
     * The header table keeps, for each item that occurs in the FP tree, a pointer to the first occurrence of that item. Each FP-node in turn keeps a pointer to the next FP-node that has the same item.
     * <p>
     * This structure creates a linked list of all nodes with the same item.
     */
    private final Map<I, FPNode<I>> headerTable = new HashMap<>();

    /**
     * The root node of the FP-tree, which is always marked with a null item and count 0.
     */
    private final FPNode<I> root;
    /**
     * A set of items that are candidate to be in an inconsistent itemset. This set is generated by invalidating items on a certain support upper bound.
     */
    private final Set<I> candidateItems = new HashSet<>();
    private final LinkedList<FPNode<I>> leafNodes = new LinkedList<>();
    private final List<FPNode<I>> leafsWithCandidates = new ArrayList<>();
    /**
     * Keeps a list of items sorted by their support (descending).
     */
    private List<I> itemOrder;

    /**
     * Create a new FPTree object with empty root node
     *
     * @param itemOrder
     */
    public FPTree(List<I> itemOrder) {
        this.itemOrder = itemOrder;
        this.root = new FPNode<>(null);
    }

    public FPNode<I> getRoot() {
        return root;
    }

    public Map<I, FPNode<I>> getHeaderTable() {
        return headerTable;
    }

    protected void build(Map<Itemset<I>, Integer> dataset, LinkedHashMap<I, Integer> itemFrequencyTable) {
        List<Itemset<I>> sorted = new ArrayList<>(dataset.keySet());

        Map<I, Integer> indices = new HashMap<>();

        int count = 0;
        for (I item : itemFrequencyTable.keySet()) {
            indices.put(item, count++);
        }

        Collections.sort(sorted, (itemset1, itemset2) -> -1 * Integer.compare(itemset1.size(), itemset2.size()));

        Map<I, FPNode<I>> currentPointerMap = new HashMap<>();

        // For each transaction, insert the items of the transaction to the FPTree object in the same order as
        // they appear in the item frequency table
        for (Itemset<I> itemset : dataset.keySet()) {
            //List<I> itemsInOrder = new ArrayList<>(itemFrequencyTable.keySet());
            //itemsInOrder.retainAll(itemset);
            List<I> itemsInOrder = new ArrayList<>(itemset);

            // TODO: filter out items from itemset that are not included in the frequency table
            itemsInOrder.retainAll(itemFrequencyTable.keySet());

            Collections.sort(itemsInOrder, (i1, i2) -> indices.get(i1).compareTo(indices.get(i2)));

            insertItemset(itemsInOrder, dataset.get(itemset), currentPointerMap);
        }
    }

    /**
     * Insert List of items to this FPTree object in order of appearance, n times.
     *
     * @param items             List of items to insert to this FPTree object
     * @param n
     * @param currentPointerMap
     */
    public void insertItemset(List<I> items, int n, Map<I, FPNode<I>> currentPointerMap) {

        // Start from the root of this FPTree object
        FPNode<I> currentNode = root;

        // Insert items one by one in the FPTree object
        for (int i = 0; i < items.size(); i++) {
            currentNode = insertItem(currentNode, items.get(i), n, i == items.size() - 1, currentPointerMap);
        }
    }

    /**
     * Returns the size of the tree in terms of nodes.
     *
     * @return
     */
    public int size() {
        return root.nodeCount();
    }

    /**
     * Returns true if the tree is empty, i.e., if the root has no children
     *
     * @return
     */
    public boolean isEmpty() {
        return root.getChildren().isEmpty();
    }

    /**
     * Checks if the tree consists of a single path. This is an operations used in the FP growth algorithm.
     *
     * @return Returns true if the tree has a single path, i.e., if there is precisely one leaf node.
     */
    public boolean isSinglePath() {
        return leafNodes.size() == 1;
    }

    /**
     * Get a List of all paths from nodes with the given item to the root.
     *
     * @param item item from which all paths to the root of the given FPTree object should start
     * @return List of all paths from given item to the root of the given FPTree object
     */
    public List<List<FPNode<I>>> getPathsToRoot(I item) {
        // Create a List of paths from the FPNode objects containing the given item to the root of the FPTree object
        List<List<FPNode<I>>> paths = new ArrayList<>();

        //Get all FP nodes that are labeled with the given item
        List<FPNode<I>> allNodesWithItem = getAllNodesWithItem(item);

        //For each of those FP nodes, add the path to the root
        for (FPNode<I> nodeWithItem : allNodesWithItem) {
            paths.add(getPathToRoot(nodeWithItem));
        }

        return paths;

    }

    /**
     * Get List of FPNode objects from the given FPNode object to the root of this FPTree object
     *
     * @param node FPNode object to construct path from to the root of this FPTree object
     * @return List of FPNode objects from the given FPNode object to the root of this FPTree object
     */
    public List<FPNode<I>> getPathToRoot(FPNode<I> node) {

        List<FPNode<I>> path = new ArrayList<>();
        path.add(node);

        while (node.getParent() != null) {
            node = node.getParent();
            path.add(node);
        }

        return path;
    }

    public int support(I item) {
        return getAllNodesWithItem(item).stream().mapToInt(node -> node.getCount()).sum();
    }

    public int support(Itemset<I> itemset) {
        return getBaseNodes(itemset)
                .stream()
                .mapToInt(node -> node.getCount())
                .sum();
    }

    /**
     * This method generates a list of candidate items that may occur in an inconsistent item set. Basically, it produces all items that occur in a part of a path that sufficiently infrequent.
     * <p>
     * Invalidating is used as a pruning method during the search for inconsistent item sets.
     *
     * @param upperBound
     */
    public void generateCandidates(int upperBound) {
        //Clear the current candidate items
        this.candidateItems.clear();
        this.leafsWithCandidates.clear();

        for (FPNode<I> leafNode : leafNodes) {
            FPNode<I> current = leafNode;

            boolean pathHasCandidate = false;
            while (current.getItem() != null && current.getCount() <= upperBound) {
                this.candidateItems.add(current.getItem());
                pathHasCandidate = true;
                current = current.getParent();
            }

            if (pathHasCandidate) {
                this.leafsWithCandidates.add(leafNode);
            }
        }
    }

    public void print() {
        this.root.print();
    }

    //
    // Supporting private methods.
    //

    /**
     * Insert one item as child of the given FPNode object. If this item is already contained in a child of the current
     * node, increment its counter
     *
     * @param currentNode FPNode object to check whether its children contain a FPNode object with given item. If not,
     *                    insert a new child, otherwise increase its counter
     * @param item        item to add as child of the current FPNode object if it does not contain such a child, otherwise
     *                    increase its counter
     * @param n           The number of times the item is inserted.
     * @return the child FPNode object of the current FPNode object containing the given item
     */
    private FPNode<I> insertItem(FPNode<I> currentNode, I item, int n, boolean leaf, Map<I, FPNode<I>> currentPointerMap) {
        FPNode<I> node = currentNode.getChild(item);

        // If a FPNode object with this item exists, increase its counter
        if (node == null) {
            // Create new FPNode object with given item and current node as parent
            node = new FPNode<>(item, currentNode, n);

            // If the header table already contains the item, add pointer to the last FPNode object containing this item,
            // otherwise, add a new entry to the header table
            if (currentPointerMap.get(item) == null) {
                headerTable.put(item, node);
            } else {
                currentPointerMap.get(item).setNextNode(node);
            }

            currentPointerMap.put(item, node);

            // Add this node as child to currentNode
            currentNode.addChild(node);

            if (leaf) {
                this.leafNodes.add(node);
            }
        } else {
            // Increase the node's counter
            node.increaseCount(n);
        }

        return node;

    }

    private List<FPNode<I>> getBaseNodes(Itemset<I> itemset) {
        I baseItem = null;

        for (int i = itemOrder.size() - 1; i >= 0; i--) {
            if (itemset.contains(itemOrder.get(i))) {
                baseItem = itemOrder.get(i);
                break;
            }
        }

        List<FPNode<I>> nodesWithItem = getAllNodesWithItem(baseItem);

        for (int i = 0; i < nodesWithItem.size(); i++) {
            final FPNode<I> n = nodesWithItem.get(i);

            if (!itemset.stream().allMatch(it -> n.hasAncestor(it))) {
                nodesWithItem.remove(i);
                i--;
            }
        }

        return nodesWithItem;
    }

    /**
     * Returns a list of all FP-nodes that are labeled with the given item.
     *
     * @param item
     * @return
     */
    private List<FPNode<I>> getAllNodesWithItem(I item) {
        List<FPNode<I>> nodesWithItem = new ArrayList<>();

        // Get the first node
        FPNode<I> currentNode = this.headerTable.get(item);

        while (currentNode != null) {
            nodesWithItem.add(currentNode);
            currentNode = currentNode.getNextNode();
        }

        return nodesWithItem;
    }

    //
    // GETTERS
    //

    /**
     * Get the set of items that are candidate to be in inconsistent itemsets.
     *
     * @return Set of items that are possibly in an itemset that is inconsistent
     */
    public Set<I> getCandidateItems() {
        return candidateItems;
    }

    /**
     * Get the order of items
     *
     * @return Sorted list of items in order of decreasing support.
     */
    public List<I> getItemOrder() {
        return itemOrder;
    }

    public List<FPNode<I>> getLeafsWithCandidates() {
        return leafsWithCandidates;
    }

    public LinkedList<FPNode<I>> getLeafNodes()
    {
        return leafNodes;
    }
}
